//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;

namespace RzWpf
{
    public class DarkenEffect : ShaderEffect
    {
        public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty( "Input", typeof( DarkenEffect ), 0 );
        public static readonly DependencyProperty DarknessProperty = DependencyProperty.Register( "Darkness", typeof( double ), typeof( DarkenEffect ), new UIPropertyMetadata( ( (double)( 0D ) ), PixelShaderConstantCallback( 0 ) ) );

        public DarkenEffect()
        {
            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri( "/RzWpf;component/Shaders/DarkenEffect.ps", UriKind.Relative );
            this.PixelShader = pixelShader;

            this.UpdateShaderValue( InputProperty );
            this.UpdateShaderValue( DarknessProperty );
        }

        public Brush Input
        {
            get{ return ( (Brush)( this.GetValue( InputProperty ) ) ); }
            set{ this.SetValue( InputProperty, value ); }
        }

        public double Darkness
        {
            get{ return ( (double)( this.GetValue( DarknessProperty ) ) ); }
            set{ this.SetValue( DarknessProperty, value ); }
        }
    }
}
