//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;

namespace RzWpf
{
    public class MultiplyEffect : ShaderEffect
    {
        public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty( "Input", typeof( MultiplyEffect ), 0 );
        public static readonly DependencyProperty ColorProperty = DependencyProperty.Register( "Color", typeof( Color ), typeof( MultiplyEffect ), new UIPropertyMetadata( Color.FromArgb( 255, 0, 0, 0 ), PixelShaderConstantCallback( 0 ) ) );

        public MultiplyEffect()
        {
            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri( "/RzWpf;component/Shaders/MultiplyEffect.ps", UriKind.Relative );
            this.PixelShader = pixelShader;

            this.UpdateShaderValue( InputProperty );
            this.UpdateShaderValue( ColorProperty );
        }

        public Brush Input
        {
            get { return ( (Brush)( this.GetValue( InputProperty ) ) ); }
            set { this.SetValue( InputProperty, value ); }
        }

        public Color Color
        {
            get { return ( (Color)( this.GetValue( ColorProperty ) ) ); }
            set { this.SetValue( ColorProperty, value ); }
        }
    }
}
