//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RzWpfTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RzWpfTest.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, the age you entered is not valid..
        /// </summary>
        internal static string Error_Age_Not_Valid {
            get {
                return ResourceManager.GetString("Error_Age_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, the name you entered is not valid..
        /// </summary>
        internal static string Error_Name_Not_Valid {
            get {
                return ResourceManager.GetString("Error_Name_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five meow.
        /// </summary>
        internal static string Five_meow {
            get {
                return ResourceManager.GetString("Five_meow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four meow.
        /// </summary>
        internal static string Four_meow {
            get {
                return ResourceManager.GetString("Four_meow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One meow.
        /// </summary>
        internal static string One_meow {
            get {
                return ResourceManager.GetString("One_meow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meow.
        /// </summary>
        internal static string TestResource {
            get {
                return ResourceManager.GetString("TestResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three meow.
        /// </summary>
        internal static string Three_meow {
            get {
                return ResourceManager.GetString("Three_meow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two meow.
        /// </summary>
        internal static string Two_meow {
            get {
                return ResourceManager.GetString("Two_meow", resourceCulture);
            }
        }
    }
}
